### ISSUE TITLE
GDLauncher won't launch on Steam Deck

### ISSUE THREAD

**Issue by zxfyr** [flathub/io.gdevs.GDLauncher#57]
To preface I am completely new to Linux. Please request more info if necessary.

The program was working on 1.29 but after the update it will not launch. The appimage from the main website does work fine. I've attached the error.

```
$ flatpak run io.gdevs.GDLauncher
[10 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[10 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[3 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[3 preload-host-spawn-strategy] Warning: waitpid override ignores groups
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot open /app/bin/gdlauncher/resources/app.asar/build/native/nsfw.node: Error: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.org.chromium.Chromium.UFIz9c)
    at Object.<anonymous> (/app/bin/gdlauncher/resources/app.asar/build/electron.js:2:2736106)
    at ./public/native/nsfw.node (/app/bin/gdlauncher/resources/app.asar/build/electron.js:2:2736144)
    at i (/app/bin/gdlauncher/resources/app.asar/build/electron.js:2:124)
    at ./public/nsfw.js (/app/bin/gdlauncher/resources/app.asar/build/electron.js:2:2736280)
    at i (/app/bin/gdlauncher/resources/app.asar/build/electron.js:2:124)
    at ./public/electron.js (/app/bin/gdlauncher/resources/app.asar/build/electron.js:2:2723428)
    at i (/app/bin/gdlauncher/resources/app.asar/build/electron.js:2:124)
    at module.exports../node_modules/base64url/dist/base64url.js (/app/bin/gdlauncher/resources/app.asar/build/electron.js:2:923)
    at Object.<anonymous> (/app/bin/gdlauncher/resources/app.asar/build/electron.js:2:953)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
Gtk-Message: 17:13:48.442: Failed to load module "canberra-gtk-module"
[3:0210/171348.498650:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0210/171348.498726:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
```

**Comment by Supertacoz** [comment]
I am having a similar issue but on a standard linux desktop. (linux mint) I have noticed that in processes everytime I try to launch GDlauncher some background processes do start as well. 
I can attach my own log, although I don't know the path to it.

**Comment by AshtakaOOf** [comment]
Yeah basically the newer version of GDLauncher (1.1.30) has switched to a newer glibc, and it seems like distro with older glibc version can't launch GDLauncher properly.
For example Fedora 37 which has glibc 2.36 can launch GDL just fine, while a distro with glibc 2.31 won't work.
And so seems like some change in the new stable version did not translate well to flatpak either.
ps: I'm just sharing what I currently know about these issues since we have a few flatpak users in the GDL discord

**Comment by nickavem** [comment]
Ok, I am finally off work, and I'm going to take a closer look. I was hoping that quick fix would get it.

**Comment by nickavem** [comment]
For now, i am going to roll the update back so things still work.
